# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 08:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resturants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resturant',
            name='location',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
