# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resturants', '0005_auto_20170725_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='resturant',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
